import type { Metadata } from "next";
import { Inter, Roboto_Condensed } from "next/font/google";
// import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import BoostrapInstall from "./components/Bootstrap";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });
const roboto_condenced = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_condenced.className}>
        <BoostrapInstall />
        {children}
      </body>
    </html>
  );
}
